<a href="https://colab.research.google.com/github/satrishabh/ML-DL-GENAI/blob/main/l1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv("/content/fraud_transactions_synthetic.csv")

In [4]:
data.head()

,amount,hour,distance_km,failed_logins_24h,is_international,is_new_device,account_age_days,txn_velocity_1h,prev_chargebacks,merchant_risk_score,is_fraud
0,33.006818,15,5.500706,1,0,0,1968,1,0,0.141327,0
1,17.491861,2,45.404859,0,0,0,883,2,1,0.249084,0
2,38.385836,5,1.889033,0,0,0,257,0,0,0.175303,0
3,92.114269,19,7.925388,0,0,0,3025,3,0,0.060368,0
4,15.892489,3,45.704719,0,0,0,1651,1,0,0.274630,1

In [9]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [10]:
x=data.drop(['is_fraud'],axis=1)
y=data['is_fraud']

In [11]:
x.head()

,amount,hour,distance_km,failed_logins_24h,is_international,is_new_device,account_age_days,txn_velocity_1h,prev_chargebacks,merchant_risk_score
0,33.006818,15,5.500706,1,0,0,1968,1,0,0.141327
1,17.491861,2,45.404859,0,0,0,883,2,1,0.249084
2,38.385836,5,1.889033,0,0,0,257,0,0,0.175303
3,92.114269,19,7.925388,0,0,0,3025,3,0,0.060368
4,15.892489,3,45.704719,0,0,0,1651,1,0,0.274630

In [12]:
y.head()

0    0
1    0
2    0
3    0
4    1
Name: is_fraud, dtype: int64

In [13]:
data.shape

(40000, 11)

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [29]:
x_test.head()

,amount,hour,distance_km,failed_logins_24h,is_international,is_new_device,account_age_days,txn_velocity_1h,prev_chargebacks,merchant_risk_score
20382,1.958935,21,19.292331,0,0,1,1902,3,0,0.111371
14197,12.918010,18,32.953810,0,0,0,2586,1,0,0.410227
2968,3.252411,14,5.211137,1,0,0,778,1,0,0.502265
23719,10.902429,13,25.797547,1,0,0,730,1,0,0.118595
14587,12.478189,18,6.943650,0,0,0,2936,0,0,0.079637

In [30]:
x_test.shape

(10000, 10)

In [16]:
x_train.shape[1]

10

In [24]:
model=keras.Sequential([
    layers.Input(shape=(x_train.shape[1],),name='input_layer'), # input has 10 neurons
    layers.Dense(16,activation='relu',name='hidden_layer_1'),# 16 neuron
    layers.Dense(32,activation='relu',name='hidden_layer_2'),# 32 neuron
    layers.Dense(1,activation='sigmoid',name='output_layer')# output_layer has just 1 neuron
])

In [25]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [26]:
model.fit(x_train,y_train,epochs=10,batch_size=32)

Epoch 1/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.9075 - loss: 5.1012
Epoch 2/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.9214 - loss: 0.5492
Epoch 3/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9248 - loss: 0.4652
Epoch 4/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9262 - loss: 0.4803
Epoch 5/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9198 - loss: 0.6166
Epoch 6/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9255 - loss: 0.4579
Epoch 7/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9261 - loss: 0.4688
Epoch 8/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9234 - loss: 0.5459
Epoch 9/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9277 - loss: 0.4691
Epoch 10/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9295 - loss: 0.4062

In [27]:
model.fit(x_train,y_train,epochs=10,batch_size=32)

Epoch 1/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9265 - loss: 0.4519
Epoch 2/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9332 - loss: 0.3537
Epoch 3/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9270 - loss: 0.4497
Epoch 4/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9321 - loss: 0.3879
Epoch 5/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9300 - loss: 0.4199
Epoch 6/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9319 - loss: 0.3565
Epoch 7/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9295 - loss: 0.4053
Epoch 8/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9319 - loss: 0.3812
Epoch 9/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9314 - loss: 0.3868
Epoch 10/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9328 - loss: 0.3543

In [28]:
y_pred=model.predict(x_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step